---
- name: Setup youtube-devops-platform
  hosts: web
  become: yes

  tasks:
    - name: Install git and docker
      dnf:
        name:
          - git
          - docker
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create app directory
      file:
        path: /opt/youtube-app
        state: directory
        owner: ec2-user
        mode: '0755'
